<a href="https://colab.research.google.com/github/Ankit-Vishvakarma/Learing_Python/blob/main/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NumPy**, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. NumPy is a Python package. It stands for 'Numerical Python'.

**Importing NumPy Library**

In [ ]:
import numpy as np
n1 = np.array([10,20,30,40])

In [ ]:
n1

array([10, 20, 30, 40])

In [ ]:
n2 = np.array([[10,20,30,40],[40,30,20,10]])

In [ ]:
n2

array([[10, 20, 30, 40],
       [40, 30, 20, 10]])

In [ ]:
type(n1)

numpy.ndarray

**To create an NumPy array initially having all Zeroes**

In [ ]:
n3 = np.zeros((2,2))

In [ ]:
n3

array([[0., 0.],
       [0., 0.]])

In [ ]:
n4 = np.zeros((10,10))

In [ ]:
n4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**To create an NumPy array initially having Specific Value**

In [ ]:
n5 = np.full((2,2),10)

In [ ]:
print(n5)

[[10 10]
 [10 10]]


**Initializing NumPy array within a range**

In [ ]:
n6 = np.arange(10,20)

In [ ]:
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
n7 = np.arange(10,50,5)

In [ ]:
n7 

array([10, 15, 20, 25, 30, 35, 40, 45])

**Initializing NumPy array with random Numbers**

In [ ]:
n8 = np.random.randint(1,100,5)

In [ ]:
n8

array([25, 25, 52, 14, 20])

**Checking the shape of the NumPy arrays**

In [ ]:
n9 = np.array([[1,2,3,4],[4,5,6,7]])

In [ ]:
n9

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [ ]:
n9.shape = (4,2)

In [ ]:
n9

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

**Joining NumPy Arrays** <br>
We can Join NumPy arrays by using **vstack(), hstack() and column_stack()** 

**vstack()**

In [ ]:
n10 = np.array([10,20,30])

In [ ]:
n11 = np.array([40,50, 60])

In [ ]:
np.vstack((n10,n11))

array([[10, 20, 30],
       [40, 50, 60]])

**hstack()**

In [ ]:
n12 = np.array([10,20,30])

In [ ]:
n13 = np.array([40,50, 60])

In [ ]:
np.hstack((n12,n12))

array([10, 20, 30, 10, 20, 30])

**column_stack()**

In [ ]:
n14 = np.array([10,20,30])

In [ ]:
n15 = np.array([40,50, 60])

In [ ]:
np.column_stack((n14,n15))

array([[10, 40],
       [20, 50],
       [30, 60]])

**NumPy Intersection & Difference**

In [ ]:
n16 = np.array([10,20,30,40,50,60])

In [ ]:
n17 = np.array([50,60,70,80,90])

In [ ]:
np.intersect1d(n16,n17)

array([50, 60])

In [ ]:
np.setdiff1d(n16,n17)

array([10, 20, 30, 40])

In [ ]:
np.setdiff1d(n17,n16)

array([70, 80, 90])

**NumPy Array Mathematics**

**Sum**

In [ ]:
n18 = np.array([1,2,3,4,5])

In [ ]:
n19 = np.array([6,7,8,9,10])

In [ ]:
np.sum([n18,n19])

55

**Add with respect to Columns**

In [ ]:
np.sum([n18,n19],axis=0)

array([ 7,  9, 11, 13, 15])

In [ ]:
np.sum([n18,n19],axis=1)

array([15, 40])

**NumPy Math Fuctions**

**Mean**

In [ ]:
np.mean(n18)

3.0

**Median**

In [ ]:
np.median(n18)

3.0

**Standard Deviation**

In [ ]:
np.std(n18)

1.4142135623730951

**NumPy Save & Load**

In [ ]:
n20 = np.array([6,7,8,9,10])

In [ ]:
np.save('my_numpy',n20)

In [ ]:
n21 = np.load('my_numpy.npy')

In [ ]:
n21

array([ 6,  7,  8,  9, 10])